// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpbqpawoewxmdiqjuemo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wYnFwYXdvZXd4bWRpcWp1ZW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODI4NTIsImV4cCI6MjA3MDc1ODg1Mn0.vtxxQX07GW-GnmeEeuTSOO1dc04IyAJ4WdEbIbdTjfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});